### ISSUE TITLE
k线图范围超出设置的container的边界了

### ISSUE THREAD

**Issue by bianxiang** [gwhcn/flutter_k_chart#11]
![image](https://user-images.githubusercontent.com/16380379/76379006-e3b23d80-6389-11ea-9266-2e75a6b248b6.png)

**Comment by gwhcn** [comment]
base_chart_painter.dart
`
void paint(Canvas canvas, Size size) {
  //增加这行代码
    canvas.clipRect(Rect.fromLTRB(0, 0, size.width, size.height));
    .....
}
`
