### ISSUE TITLE
Failed assertion: line 21 pos 12: '_current != null'

### ISSUE THREAD

**Issue by monxarat** [gwhcn/flutter_k_chart#17]
Hy guys,

How to resolve this issue?

======== Exception caught by widgets library =======================================================
The following assertion was thrown building Container(constraints: BoxConstraints(w=Infinity, h=450.0), margin: EdgeInsets(10.0, 0.0, 10.0, 0.0)):
No instance of S was loaded. Try to initialize the S delegate before accessing S.current.
'package:flutter_k_chart/generated/l10n.dart':
Failed assertion: line 21 pos 12: '_current != null'

**Comment by gwhcn** [comment]
Need to configure internationalization
```
import 'package:flutter_k_chart/generated/l10n.dart' as k_chart;
//.....
MaterialApp(
//here
localizationsDelegates: [ k_chart.S.delegate ],
)

```

**Comment by monxarat** [comment]
@gwhcn 
Big thank.
