### ISSUE TITLE
计算BOLL,为什么要判断 < 19

### ISSUE THREAD

**Issue by deboLing** [gwhcn/flutter_k_chart#3]
static void calcBOLL(List<KLineEntity> dataList) {
    for (int i = 0; i < dataList.length; i++) {
      KLineEntity entity = dataList[i];
      if (i < 19) {
        entity.mb = 0;
        entity.up = 0;
        entity.dn = 0;
      } else {
        int n = 20;
        double md = 0;
        for (int j = i - n + 1; j <= i; j++) {
          double c = dataList[j].close;
          double m = entity.MA20Price;
          double value = c - m;
          md += value * value;
        }
        md = md / (n - 1);
        md = sqrt(md);
        entity.mb = entity.MA20Price;
        entity.up = entity.mb + 2.0 * md;
        entity.dn = entity.mb - 2.0 * md;
      }
    }
  }
为什么要判断 i< 19？

**Comment by gwhcn** [comment]
因为中轨线是ma20，小于20就不画线

**Comment by deboLing** [comment]
嗯 后来对比tradingView，算是看明白了，是这么一回事
