### ISSUE TITLE
关于引入问题

### ISSUE THREAD

**Issue by LvJson** [gwhcn/flutter_k_chart#4]
您好，请问如何引入到自己的项目中去？

**Comment by gwhcn** [comment]
在项目外层目录新建一个plugins文件夹，和lib是平级的，把flutter_k_chart放plugins目录下，然后在pubspec文件里面声明：
flutter_k_chart:
    path: plugins/flutter_k_chart

**Comment by LvJson** [comment]
这种办法也行，只是没有直接引入来的方便，如果你有版本变化的话。

**Comment by gwhcn** [comment]
目前封装的不是很好，修改ui必须得改源码，所以必须本地引入源码

**Comment by LvJson** [comment]
好的，明白了，谢谢！！！
