### ISSUE TITLE
分时图渐变色问题

### ISSUE THREAD

**Issue by LvJson** [gwhcn/flutter_k_chart#6]
我把flutter_k_chart和其它widget组合使用时发现个问题，当切换到分时图时，分时图下面的控件背景受到了分时图背景色影响。假如我把底部控件的颜色设置成白色，实际显示的却是分时图的背景色。

**Comment by gwhcn** [comment]
模仿火币时写死了，可以自行修改ChartPainter类下drawBg()方法修改颜色
